# This is a basic workflow to help you get started with Actions

name: Build FastDeploy Libraries

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the regression2 branch
on:
  push:
    branches: [ master ]

env:
  OPENCV_VER: 4.5.3
  FASTDEPLOY_VER: gac255b8a
  FASTDEPLOY_REF: ac255b8ab8c888fa96299715e2f9802cf3d722c0

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-fastdeploy:

    strategy:
      matrix:
        os: [ubuntu, windows]
        include:
          - os: macos
            arch: arm64
          - os: macos
            arch: x86_64

    defaults:
      run:
        shell: bash
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup macOS Environment
        if: runner.os == 'macOS'
        run: |
          brew unlink python
          brew link --overwrite python

      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1
        with:
          windows_compile_environment: msvc

      - name: Install Linux Packages
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake

      - uses: ilammy/msvc-dev-cmd@v1
        id: msvc-env
        if: runner.os == 'Windows'

      - name: Get specific version CMake, v3.24.3
        if: runner.os == 'Windows'
        uses: lukka/get-cmake@v3.24.3

      - name: Setup package suffix
        run: |
          PKG_SUFFIX=${{ runner.os }}
          [[ ${{ matrix.os }} = "macos" ]] && PKG_SUFFIX=$PKG_SUFFIX-${{ matrix.arch }}
          echo "PKG_SUFFIX=${PKG_SUFFIX}" >> $GITHUB_ENV

      - name: Download OpenCV
        uses: robinraju/release-downloader@v1.6
        with:
          repository: "MaaAssistantArknights/build-opencv"
          tag: ${{ env.OPENCV_VER }}
          fileName: OpenCV-${{ env.PKG_SUFFIX }}.tar.gz

      - name: Extract OpenCV
        run: |
          cd ${GITHUB_WORKSPACE}
          tar -zxvf OpenCV-${{ env.PKG_SUFFIX }}.tar.gz

      - name: Clone FastDeploy
        uses: actions/checkout@v3
        with:
          repository: PaddlePaddle/FastDeploy
          path: FastDeploy
          ref: ${{ env.FASTDEPLOY_REF }}

      - name: Setup MSVC environment
        if: runner.os == 'Windows'
        run: |
            echo "CMAKE_GENERATOR=Ninja" >> $GITHUB_ENV
            echo "CC=cl" >> $GITHUB_ENV
            echo "CXX=cl" >> $GITHUB_ENV
            echo "OpenCV=/lib" >> $GITHUB_ENV

      - name: Patch FastDeploy CMake for macOS
        if: runner.os == 'macOS'
        run: |
            cd ${GITHUB_WORKSPACE}/FastDeploy
            sed -i'' -e '/-D_GLIBCXX_USE_CXX11_ABI/d' CMakeLists.txt
            sed -i'' -e '/-D_GLIBCXX_USE_CXX11_ABI/d' FastDeploy.cmake.in

      - name: Configure FastDeploy
        run: |
            cd ${GITHUB_WORKSPACE}/FastDeploy
            mkdir build && cd build
            cmake \
              -DCMAKE_BUILD_TYPE=Release \
              -DENABLE_ORT_BACKEND=ON \
              -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/build/fastdeploy \
              -DENABLE_VISION=ON \
              -DOPENCV_DIRECTORY=${GITHUB_WORKSPACE}/opencv${OpenCV} \
              -DCMAKE_INSTALL_RPATH='$ORIGIN/:$ORIGIN/../third_libs/install/onnxruntime/lib:$ORIGIN/../third_libs/install/paddle2onnx/lib' \
              ..

      - name: Extra configuration for Windows
        if: runner.os == 'Windows'
        run: |
            cd ${GITHUB_WORKSPACE}/FastDeploy/build
            cmake .. \
              -DCMAKE_CXX_COMPILER_LAUNCHER:FILEPATH="${{ env.ccache_symlinks_path }}"

      - name: Extra configuration for macOS
        if: runner.os == 'macOS'
        run: |
            cd ${GITHUB_WORKSPACE}/FastDeploy/build
            cmake .. \
              -DCMAKE_OSX_ARCHITECTURES="${{ matrix.arch }}" \
              -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0

      - name: Build FastDeploy
        run: |
            cd ${GITHUB_WORKSPACE}/FastDeploy/build
            cmake --build . --config Release --target install --parallel ${PARALLEL_JOBS:-$(nproc --all)}

      - name: Patch FastDeploy
        run: |
            cd ${GITHUB_WORKSPACE}/build/fastdeploy
            sed -i'' -e '/set(OPENCV_DIRECTORY/d' FastDeploy.cmake
            
      - name: Package FastDeploy
        run: |
            cd ${GITHUB_WORKSPACE}/build
            tar -czvf FastDeploy-${{ env.PKG_SUFFIX }}.tar.gz fastdeploy


      - name: Upload FastDeploy
        uses: actions/upload-artifact@v3
        with:
          name: fastdeploy-${{ env.PKG_SUFFIX }}
          path: build/FastDeploy-${{ env.PKG_SUFFIX }}.tar.gz


  upload-release:
    needs: build-fastdeploy
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: download

      - name: Move files
        run: |
            cd ${GITHUB_WORKSPACE}
            mkdir release
            mv download/*/* ${GITHUB_WORKSPACE}/release/
            cd ${GITHUB_WORKSPACE}/release
            sha256sum --tag * > ${GITHUB_WORKSPACE}/hashes.txt

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: hashes.txt
          tag_name: ${{ env.FASTDEPLOY_VER }}
          files: |
            release/*

